import { TRPCError } from "@trpc/server";
import type { Request as ExRequest, Response as ExResponse, Application as ExApp, NextFunction as ExNext } from "express";
import { z } from "zod";
import { COOKIE_NAME, ONE_YEAR_MS } from "../shared/const.js";
import { getSessionCookieOptions } from "./_core/cookies.js";
import { systemRouter } from "./_core/systemRouter.js";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc.js";
import { sdk } from "./_core/sdk.js";
import { addComment, addUpvote, createLocation, createNotification, createTicket, createLocalUser, deleteLocation, deleteTicket, deleteUser, flagHoax, getPublicProfile, getTicket, getUserById, getUserByLogin, getUserByOpenId, getUserProfile, hashPassword, hasUpvoted, importUsers, isLeadEmail, COMMUNITY_VALIDATION_THRESHOLD, listComments, listHoaxFlags, listLocations, listNotifications, listUnverifiedLocations, listUnreadNotifications, listTickets, listTechnicians, listUsers, markNotificationsRead, reportUser, seedLocations, setUserBanned, setUserPassword, updateComment, updateLocation, updateTicket, updateUser, updateUserImage, updateUserRole, updateUsername, upsertUser, verifyLocation, verifyPassword } from "./db.js";

const roleSchema = z.enum(["user", "admin", "tech"]);
async function ensureValidated(ticketId: number, status: string) { const ticket = await getTicket(ticketId); if (!ticket) throw new TRPCError({ code: "NOT_FOUND", message: "Ticket not found." }); if ((status === "approved" || status === "assigned" || status === "resolved") && ticket.upvoteCount < COMMUNITY_VALIDATION_THRESHOLD) throw new TRPCError({ code: "PRECONDITION_FAILED", message: `Community validation needs at least ${COMMUNITY_VALIDATION_THRESHOLD} support.` }); return ticket; }
const statusSchema = z.enum(["pending", "approved", "assigned", "in_progress", "resolved"]);
const urgencySchema = z.enum(["low", "medium", "high", "critical"]); const categorySchema = z.enum(["AC", "Elevator", "Door", "Lighting", "Seat", "Toilet", "Escalator", "Other"]);
const leadOnly = protectedProcedure.use(({ ctx, next }) => {
  if (!isLeadEmail(ctx.user.email)) throw new TRPCError({ code: "FORBIDDEN", message: "Only FasiliCare leads can use God Mode." });
  return next();
});
const techProcedure = protectedProcedure.use(({ ctx, next }) => {
  if (ctx.user.role !== "tech") throw new TRPCError({ code: "FORBIDDEN", message: "Technician access required." });
  return next();
});

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => { ctx.res.clearCookie(COOKIE_NAME, { ...getSessionCookieOptions(ctx.req), maxAge: -1 }); return { success: true } as const; }),
    register: publicProcedure.input(z.object({ email: z.string().email(), username: z.string().trim().min(3).max(64).regex(/^[a-zA-Z0-9_.-]+$/), password: z.string().min(8).max(128) })).mutation(async ({ ctx, input }) => {
      if (await getUserByLogin(input.email)) throw new TRPCError({ code: "CONFLICT", message: "Email already registered." });
      if (await getUserByLogin(input.username)) throw new TRPCError({ code: "CONFLICT", message: "Username already taken." });
      const user = await createLocalUser(input); const token = await sdk.createSessionToken(user.openId, { name: user.name ?? input.username, email: user.email, role: user.role }); ctx.res.cookie(COOKIE_NAME, token, { ...getSessionCookieOptions(ctx.req), maxAge: ONE_YEAR_MS }); return { success: true as const };
    }),
      adminPassword: adminProcedure.input(z.object({ userId: z.number().int().positive(), password: z.string().min(8).max(128) })).mutation(({ input }) => setUserPassword(input.userId, input.password)),
    login: publicProcedure.input(z.object({ login: z.string().trim().min(1), password: z.string().min(1) })).mutation(async ({ ctx, input }) => {
      const user = await getUserByLogin(input.login); if (!user?.passwordHash || !(await verifyPassword(input.password, user.passwordHash))) throw new TRPCError({ code: "UNAUTHORIZED", message: "Invalid email/username or password." }); if (user.isBanned) throw new TRPCError({ code: "FORBIDDEN", message: "This account is banned." }); const token = await sdk.createSessionToken(user.openId, { name: user.name ?? user.username ?? "User", email: user.email, role: user.role }); ctx.res.cookie(COOKIE_NAME, token, { ...getSessionCookieOptions(ctx.req), maxAge: ONE_YEAR_MS }); return { success: true as const };
    }),
    demoLogin: publicProcedure.input(z.object({ role: roleSchema })).mutation(async ({ ctx, input }) => {
      const profiles = { admin: { openId: "demo-admin", name: "Demo Admin", email: "demo.admin@fasilicare.local" }, user: { openId: "demo-commuter", name: "Demo Commuter", email: "demo.commuter@fasilicare.local" }, tech: { openId: "demo-technician", name: "Demo Technician", email: "demo.tech@fasilicare.local" } } as const;
      const profile = profiles[input.role];
      await upsertUser({ ...profile, role: input.role, loginMethod: "demo", lastSignedIn: new Date() });
      const persistedProfile = await getUserByOpenId(profile.openId);
      const token = await sdk.createSessionToken(profile.openId, { name: profile.name });
      ctx.res.cookie(COOKIE_NAME, token, { ...getSessionCookieOptions(ctx.req), maxAge: ONE_YEAR_MS });
      return { success: true as const, userId: persistedProfile?.id ?? 0 };
    }),
  }),
  locations: router({ list: publicProcedure.query(() => listLocations()), seed: protectedProcedure.mutation(() => seedLocations()), create: protectedProcedure.input(z.object({ name: z.string().trim().min(2).max(180), type: z.string().trim().max(40).default("Custom"), isVerified: z.boolean().optional() })).mutation(({ ctx, input }) => createLocation(input.name, input.type).then(location => ctx.user.role === "admin" && input.isVerified !== false ? updateLocation(location.id, { isVerified: true }) : location)), unverified: adminProcedure.query(() => listUnverifiedLocations()), update: adminProcedure.input(z.object({ locationId: z.number().int().positive(), name: z.string().trim().min(2).max(180), type: z.string().trim().max(40), isVerified: z.boolean() })).mutation(({ input }) => updateLocation(input.locationId, { name: input.name, type: input.type, isVerified: input.isVerified })), verify: adminProcedure.input(z.object({ locationId: z.number().int().positive() })).mutation(({ input }) => verifyLocation(input.locationId, true)), remove: adminProcedure.input(z.object({ locationId: z.number().int().positive() })).mutation(({ input }) => deleteLocation(input.locationId)) }),
  tickets: router({
    feed: publicProcedure.query(() => listTickets(["pending", "in_progress"])),
    resolved: publicProcedure.query(() => listTickets(["resolved"])),
    detail: publicProcedure.input(z.object({ ticketId: z.number().int().positive() })).query(({ input }) => getTicket(input.ticketId)),
    comments: publicProcedure.input(z.object({ ticketId: z.number().int().positive() })).query(({ input }) => listComments(input.ticketId)),
    mine: protectedProcedure.query(({ ctx }) => listTickets(undefined, undefined, ctx.user.id)),
    triage: adminProcedure.query(() => listTickets(["pending", "approved", "assigned", "in_progress"])),
    tasks: techProcedure.query(({ ctx }) => listTickets(["assigned", "in_progress"], undefined, undefined, ctx.user.id)),
    create: protectedProcedure.input(z.object({ issueDesc: z.string().trim().min(12).max(500), category: categorySchema.default("Other"), photoUrl: z.string().url(), locationId: z.number().int().positive(), urgency: urgencySchema.default("low") })).mutation(({ ctx, input }) => createTicket({ ...input, authorId: ctx.user.id })),
    recentAtLocation: protectedProcedure.input(z.object({ locationId: z.number().int().positive() })).query(({ input }) => listTickets(["pending", "approved", "assigned", "in_progress"], input.locationId)),
    upvote: protectedProcedure.input(z.object({ ticketId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { if (await hasUpvoted(ctx.user.id, input.ticketId)) throw new TRPCError({ code: "CONFLICT", message: "You already supported this report." }); return addUpvote(ctx.user.id, input.ticketId); }),
    updateStatus: adminProcedure.input(z.object({ ticketId: z.number().int().positive(), status: z.enum(["approved", "assigned", "in_progress"]) })).mutation(async ({ input }) => { await ensureValidated(input.ticketId, input.status); return updateTicket(input.ticketId, { status: input.status }); }),
    adminEdit: adminProcedure.input(z.object({ ticketId: z.number().int().positive(), issueDesc: z.string().trim().min(12).max(500), category: categorySchema, urgency: urgencySchema.default("low"), status: statusSchema })).mutation(async ({ input }) => { await ensureValidated(input.ticketId, input.status); return updateTicket(input.ticketId, { issueDesc: input.issueDesc, category: input.category, urgency: input.urgency, status: input.status }); }),
    technicians: adminProcedure.query(() => listTechnicians()),
    assign: adminProcedure.input(z.object({ ticketId: z.number().int().positive(), technicianId: z.number().int().positive() })).mutation(async ({ input }) => { const technicians = await listTechnicians(); if (!technicians.some(tech => tech.id === input.technicianId)) throw new TRPCError({ code: "BAD_REQUEST", message: "Selected user is not a technician." }); await ensureValidated(input.ticketId, "assigned"); return updateTicket(input.ticketId, { assignedTechId: input.technicianId, status: "assigned" }); }),
    adminDelete: adminProcedure.input(z.object({ ticketId: z.number().int().positive() })).mutation(({ input }) => deleteTicket(input.ticketId)),
    startRepair: techProcedure.input(z.object({ ticketId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const ticket = await getTicket(input.ticketId); if (!ticket || ticket.assignedTechId !== ctx.user.id) throw new TRPCError({ code: "FORBIDDEN", message: "This ticket is not assigned to you." }); if (ticket.status !== "assigned") throw new TRPCError({ code: "PRECONDITION_FAILED", message: "This ticket is not ready to start." }); return updateTicket(input.ticketId, { status: "in_progress", startedAt: new Date() }); }),
    resolve: techProcedure.input(z.object({ ticketId: z.number().int().positive(), proofUrl: z.string().url() })).mutation(async ({ ctx, input }) => { const ticket = await getTicket(input.ticketId); if (!ticket || ticket.assignedTechId !== ctx.user.id) throw new TRPCError({ code: "FORBIDDEN", message: "This ticket is not assigned to you." }); if (ticket.status !== "in_progress") throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Start the ticket before resolving it." }); return updateTicket(input.ticketId, { status: "resolved", proofUrl: input.proofUrl, resolvedAt: new Date() }); }),
    addComment: protectedProcedure.input(z.object({ ticketId: z.number().int().positive(), text: z.string().trim().min(2).max(500) })).mutation(({ ctx, input }) => addComment({ ...input, userId: ctx.user.id })),
    editComment: protectedProcedure.input(z.object({ commentId: z.number().int().positive(), text: z.string().trim().min(2).max(500) })).mutation(({ ctx, input }) => updateComment(input.commentId, ctx.user.id, input.text)),
    flagHoax: protectedProcedure.input(z.object({ ticketId: z.number().int().positive(), reason: z.string().trim().max(500).optional() })).mutation(({ ctx, input }) => flagHoax({ ...input, reporterId: ctx.user.id })),
  }),
  admin: router({ users: adminProcedure.query(() => listUsers()), updateUserRole: adminProcedure.input(z.object({ userId: z.number().int().positive(), role: roleSchema })).mutation(({ input }) => updateUserRole(input.userId, input.role)), updateUser: adminProcedure.input(z.object({ userId: z.number().int().positive(), name: z.string().trim().max(200).nullable().optional(), email: z.string().email().nullable().optional(), role: roleSchema.optional(), reputationPoints: z.number().int().min(0).optional(), isBanned: z.boolean().optional() })).mutation(({ input }) => updateUser(input.userId, input)), banUser: adminProcedure.input(z.object({ userId: z.number().int().positive(), isBanned: z.boolean() })).mutation(({ input }) => setUserBanned(input.userId, input.isBanned)), removeAvatar: adminProcedure.input(z.object({ userId: z.number().int().positive() })).mutation(({ input }) => updateUserImage(input.userId, null)), importUsers: adminProcedure.input(z.array(z.object({ openId: z.string().min(1), name: z.string().nullable().optional(), email: z.string().email().nullable().optional(), role: roleSchema.optional() }))).mutation(({ input }) => importUsers(input)), hoaxFlags: adminProcedure.query(() => listHoaxFlags()), deleteUser: adminProcedure.input(z.object({ userId: z.number().int().positive() })).mutation(({ input }) => deleteUser(input.userId)), tickets: adminProcedure.query(() => listTickets()), editTicket: adminProcedure.input(z.object({ ticketId: z.number().int().positive(), issueDesc: z.string().trim().min(12).max(500), category: categorySchema, urgency: urgencySchema, status: statusSchema })).mutation(({ input }) => updateTicket(input.ticketId, { issueDesc: input.issueDesc, category: input.category, urgency: input.urgency, status: input.status })), forceUpdate: adminProcedure.input(z.object({ ticketId: z.number().int().positive(), status: statusSchema })).mutation(({ input }) => updateTicket(input.ticketId, { status: input.status })), deleteTicket: adminProcedure.input(z.object({ ticketId: z.number().int().positive() })).mutation(({ input }) => deleteTicket(input.ticketId)) }),
  publicProfiles: router({ detail: publicProcedure.input(z.object({ userId: z.number().int().positive() })).query(({ input }) => getPublicProfile(input.userId)), report: protectedProcedure.input(z.object({ userId: z.number().int().positive(), reason: z.string().trim().max(500).optional() })).mutation(({ ctx, input }) => reportUser(ctx.user.id, input.userId, input.reason)) }),
  analytics: adminProcedure.query(async () => { const [rows, people] = await Promise.all([listTickets(), listUsers()]); const byCategory = rows.reduce<Record<string, number>>((acc, row) => { const key = row.category || "Other"; acc[key] = (acc[key] || 0) + 1; return acc; }, {}); const byLocation = rows.reduce<Record<string, number>>((acc, row) => { const key = row.locationName || "Unknown"; acc[key] = (acc[key] || 0) + 1; return acc; }, {}); const topUsers = [...people].sort((a, b) => (b.reputationPoints ?? b.reputation) - (a.reputationPoints ?? a.reputation)).slice(0, 3); return { total: rows.length, resolved: rows.filter(row => row.status === "resolved").length, byCategory, byLocation, topUsers }; }),
  notifications: router({
    unread: protectedProcedure.query(({ ctx }) => listUnreadNotifications(ctx.user.id)), history: protectedProcedure.query(({ ctx }) => listNotifications(ctx.user.id)),
    markRead: protectedProcedure.mutation(({ ctx }) => markNotificationsRead(ctx.user.id)),
  }),
  user: router({
    role: leadOnly.input(z.object({ role: roleSchema })).mutation(async ({ ctx, input }) => { const dbUser = ctx.user.id > 0 ? ctx.user : await getUserByOpenId(ctx.user.openId); if (!dbUser?.id) throw new TRPCError({ code: "NOT_FOUND", message: "User profile not found." }); return updateUserRole(dbUser.id, input.role); }),
    profile: protectedProcedure.query(async ({ ctx }) => { const dbUser = ctx.user.id > 0 ? ctx.user : await getUserByOpenId(ctx.user.openId); return dbUser?.id ? getUserProfile(dbUser.id) : undefined; }),
    updateUsername: protectedProcedure.input(z.object({ username: z.string().trim().min(3).max(64).regex(/^[a-zA-Z0-9_.-]+$/) })).mutation(async ({ ctx, input }) => { const existing = await getUserByLogin(input.username); if (existing && existing.openId !== ctx.user.openId) throw new TRPCError({ code: "CONFLICT", message: "Username already taken." }); const dbUser = ctx.user.id > 0 ? ctx.user : await getUserByOpenId(ctx.user.openId); if (!dbUser?.id) throw new TRPCError({ code: "NOT_FOUND", message: "User profile not found." }); return updateUsername(dbUser.id, input.username); }),
    changePassword: protectedProcedure.input(z.object({ currentPassword: z.string().optional(), newPassword: z.string().min(8).max(128) })).mutation(async ({ ctx, input }) => { const dbUser = ctx.user.id > 0 ? ctx.user : await getUserByOpenId(ctx.user.openId); if (!dbUser?.id) throw new TRPCError({ code: "NOT_FOUND", message: "User profile not found." }); const fullUser = await getUserById(dbUser.id); if (fullUser?.passwordHash && (!input.currentPassword || !(await verifyPassword(input.currentPassword, fullUser.passwordHash)))) throw new TRPCError({ code: "UNAUTHORIZED", message: "Current password is invalid." }); await setUserPassword(dbUser.id, input.newPassword); return { success: true as const }; }),
    updateImage: protectedProcedure.input(z.object({ image: z.string().url() })).mutation(async ({ ctx, input }) => { const dbUser = ctx.user.id > 0 ? ctx.user : await getUserByOpenId(ctx.user.openId); if (!dbUser?.id) throw new TRPCError({ code: "NOT_FOUND", message: "User profile not found." }); return updateUserImage(dbUser.id, input.image); }),
  }),
});
export type AppRouter = typeof appRouter;
