import { ArrowLeft, Shield, Trash2, UserCog } from "lucide-react";
import { Link } from "wouter";
import { Footer, Navbar } from "@/components/FasiliCareShell";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

export default function AdminUsers() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const q = trpc.admin.users.useQuery();
  const role = trpc.admin.updateUserRole.useMutation({ onSuccess: () => { toast.success("Role updated"); utils.admin.users.invalidate(); }, onError: e => toast.error(e.message) });
  const remove = trpc.admin.deleteUser.useMutation({ onSuccess: () => { toast.success("User deleted"); utils.admin.users.invalidate(); }, onError: e => toast.error(e.message) });
  if (user?.role !== "admin") return <><Navbar /><main className="mx-auto max-w-xl px-5 py-24 text-center"><h1 className="text-3xl font-black">Admin access required</h1><Link href="/" className="mt-4 inline-block font-bold text-orange-600">Return home</Link></main></>;
  return <div className="min-h-screen bg-[#fffaf2]"><Navbar /><main className="mx-auto max-w-6xl px-5 py-10"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft className="size-4" /> Operations</Link><div className="mt-8 flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-orange-600">Admin / people</p><h1 className="mt-2 text-4xl font-black">User management</h1><p className="mt-2 text-slate-600">Assign the right access level to each FasiliCare contributor.</p></div><div className="rounded-2xl bg-[#102a43] px-5 py-3 text-white"><span className="text-2xl font-black">{q.data?.length ?? 0}</span><span className="ml-2 text-sm text-slate-300">accounts</span></div></div><div className="mt-8 overflow-hidden rounded-3xl bg-white shadow-[0_8px_35px_rgba(16,42,67,.07)]"><div className="hidden grid-cols-[1fr_150px_110px_130px] gap-4 border-b border-slate-100 px-5 py-4 text-xs font-black uppercase tracking-wider text-slate-400 md:grid"><span>Contributor</span><span>Role</span><span>Points</span><span>Actions</span></div>{q.isLoading ? <p className="p-8 text-center text-slate-500">Loading users…</p> : q.data?.map(item => <div key={item.id} className="grid gap-4 border-b border-slate-100 px-5 py-5 last:border-0 md:grid-cols-[1fr_150px_110px_130px] md:items-center"><div className="flex items-center gap-3">{item.image ? <img src={item.image} alt="" className="size-11 rounded-2xl object-cover" /> : <div className="grid size-11 place-items-center rounded-2xl bg-orange-100 font-black text-orange-700">{item.name?.[0] || "?"}</div>}<div><Link href={`/profile/${item.id}`} className="font-bold text-[#102a43] hover:text-orange-600">{item.name || "Unnamed commuter"}</Link><p className="text-xs text-slate-400">{item.email || "No email"}</p></div></div><div><Badge className="rounded-full bg-orange-100 text-orange-700">{item.role}</Badge></div><p className="font-black text-[#102a43]">{item.reputation} pts</p><div className="flex gap-2"><select aria-label={`Role for ${item.name || item.email}`} value={item.role} onChange={e => role.mutate({ userId: item.id, role: e.target.value as "user" | "admin" | "tech" })} className="h-9 rounded-lg border border-slate-200 bg-white px-2 text-xs font-bold"><option value="user">user</option><option value="tech">tech</option><option value="admin">admin</option></select><Button aria-label={`Delete ${item.name || item.email}`} disabled={item.id === user.id} onClick={() => window.confirm(`Delete ${item.name || "this user"}? Their authored tickets will also be removed.`) && remove.mutate({ userId: item.id })} variant="outline" className="size-9 rounded-lg border-red-200 p-0 text-red-600"><Trash2 className="size-4" /></Button></div></div>)}</div></main><Footer /></div>;
}
